-- =============================================================================
-- BASELINE — the database as it was BEFORE changes were tracked (before
-- 2026-10-04). Written from the live schema snapshot of 2026-10-08
-- (supabase/tools/snapshot-2026-10-08.json) minus what the later migrations
-- added. The tables were originally created by hand in the Supabase dashboard.
--
-- ⚠️ DO NOT RUN THIS ON THE LIVE DATABASE — it already has all of this.
-- It exists so the full structure is documented and can be rebuilt on a new,
-- empty project (e.g. a future Supabase Pro / staging project), followed by
-- the other files in this folder, in order. Safe to re-run (if not exists).
--
-- Notes:
--   * places.lat / places.lng may have been NOT NULL originally; the
--     2026-10-07 migration makes them optional either way.
--   * dispatches and security_alerts come from the earlier Kinshasa Portal
--     (journalism) app; the current site does not use them.
--   * security_alerts.commune uses a custom enum type in the live database
--     whose values are not in the snapshot; it is recorded as text here.
--   * Row-level security is enabled on every table (policies are set by
--     20261004120000_security_hardening.sql and later files).
-- =============================================================================

create table if not exists public.places (
  id bigint generated by default as identity primary key,
  name text not null,
  commune text not null,
  vertical text not null,
  description text,
  address text,
  budget text default '$$',
  lat double precision,
  lng double precision,
  image_url text,
  is_label_recommended boolean default true,
  created_at timestamptz default now(),
  google_maps_url text,
  likes integer default 0,
  dislikes integer not null default 0,
  rating_sum integer not null default 0,
  rating_count integer not null default 0
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  place_id bigint references public.places(id) on delete cascade,
  author_name text default 'Visiteur',
  comment_text text not null,
  created_at timestamptz default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  commune text not null,
  event_date date not null,
  category text default 'Weekend Event',
  description text,
  image_url text,
  url text,
  is_weekend_featured boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  commune text,
  source_note text,
  link_url text,
  published_date date not null default current_date,
  created_at timestamptz not null default now()
);

create table if not exists public.banners (
  id bigint generated by default as identity primary key,
  message text,
  link_url text,
  link_label text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  image_url text
);

create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.partner_inquiries (
  id bigint generated by default as identity primary key,
  company_name text not null,
  contact_name text,
  email text not null,
  phone text,
  message text,
  created_at timestamptz not null default now()
);

-- Legacy (earlier Kinshasa Portal journalism app) -----------------------------
create table if not exists public.dispatches (
  id bigint generated by default as identity primary key,
  commune text not null,
  category text not null default 'security',
  title text not null,
  details text not null,
  author text default 'Press Desk',
  created_at timestamptz default now(),
  content text,
  url text
);

create table if not exists public.security_alerts (
  id bigserial primary key,
  commune text not null,              -- live: custom enum type (values not recorded)
  title varchar not null,
  description text not null,
  severity varchar not null check (severity in ('low', 'medium', 'high')),
  created_at timestamptz default current_timestamp,
  expires_at timestamptz,
  journalist_id uuid references auth.users(id)
);

do $$
declare t text;
begin
  foreach t in array array['places','comments','events','news','banners','subscribers','partner_inquiries','dispatches','security_alerts'] loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end $$;

-- Legacy policies, recorded exactly as they are live (2026-10-08 snapshot).
-- ⚠️ "Allow authenticated insert dispatches" is applied to role `public` with
-- check (true): despite its name, ANYONE (no login) can add rows to
-- dispatches. See supabase/pending/ for the optional fix.
drop policy if exists "Allow authenticated insert dispatches" on public.dispatches;
create policy "Allow authenticated insert dispatches" on public.dispatches for insert to public with check (true);
drop policy if exists "Allow public read dispatches" on public.dispatches;
create policy "Allow public read dispatches" on public.dispatches for select to public using (true);
drop policy if exists "Enable read access for all users" on public.dispatches;
create policy "Enable read access for all users" on public.dispatches for select to public using (true);
drop policy if exists "Allow authenticated insert" on public.security_alerts;
create policy "Allow authenticated insert" on public.security_alerts for insert to public with check (auth.role() = 'authenticated');
drop policy if exists "Allow public read access" on public.security_alerts;
create policy "Allow public read access" on public.security_alerts for select to public using (true);

-- Storage buckets (public) ------------------------------------------------------
insert into storage.buckets (id, name, public) values ('banners', 'banners', true) on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('commune-videos', 'commune-videos', true) on conflict (id) do nothing;
